### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [DieZzZeL2021/SkillUp#1]
1)
ваш стиль должен подключаться самым последним, а не первым
![image](https://user-images.githubusercontent.com/8464662/121007949-1ae4e980-c79b-11eb-9343-48796f731977.png)

2)
внешний вид не соответствует задаче
![image](https://user-images.githubusercontent.com/8464662/121008102-48319780-c79b-11eb-90e9-b5aca92dcc09.png)

3)
внешний вид не соответствует задаче
![image](https://user-images.githubusercontent.com/8464662/121008290-83cc6180-c79b-11eb-9c40-ae3f919f74d7.png)
![image](https://user-images.githubusercontent.com/8464662/121008318-8af36f80-c79b-11eb-95af-83064bf9b069.png)

**Comment by DieZzZeL2021** [comment]
Пофиксил вроде)
https://diezzzel2021.github.io/SkillUp/
https://github.com/DieZzZeL2021/SkillUp

пн, 7 июн. 2021 г. в 14:21, Andrey ***@***.***>:

**Comment by Alecto** [comment]
похоже на то.
работа принята.
в переписке потерялась Имя Фамилия, группа.
напомните пожалуйста.

вт, 8 июн. 2021 г. в 14:51, DieZzZeL2021 ***@***.***>:

**Comment by Alecto** [comment]
https://github.com/DieZzZeL2021/Kinozal/issues/1

вт, 8 июн. 2021 г. в 15:03, DieZzZeL2021 ***@***.***>:

> У меня еще готов проект "Кинозал"

не готов

**Comment by DieZzZeL2021** [comment]
Сысоенко Анатолий FE2104 (сб/вс 9:30)
Отлично, буду фиксить кинозал

вт, 8 июн. 2021 г. в 16:38, Andrey ***@***.***>:
